### PR TITLE
Components setup split in modules

### PR DESCRIPTION
**Pull request by feliun**
This is a first step to ease the service generation from a template. 

Please let me know.

### CODE REVIEW

**Comment by cressie176** [comment]
I'm going to try a slightly different approach - systemic has the option of including components from another system (was previously called ```merge```).  I'm going to start with...

```
system
  .configure(config)
  .include(basics)
  .include(postgres)
  .add('whatever', ...)
```

then see if I can get it to work with

```
system
  .configure(config)
  .include(components) // includes basics and postgres
  .add('whatever', ...)
```

**Comment by feliun** [comment]
Can we work on that from this PR? I included some fixes for master as well (like the 1st commit)

**Comment by cressie176** [comment]
I need some time to experiment. I think it will be more difficult to start from this PR. The code I committed yesterday has the same fix.

**Comment by cressie176** [comment]
I've pushed an alternative approach where the components are defined as sub systems. I still want to dynamically discover the components in system.js. See what you think...

**Comment by cressie176** [comment]
dynamic discovery is done. system.js looks a lot nicer now.

**Pull request closed without merging**
